name: Vercel Preview
on:
  pull_request:
  workflow_dispatch:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          cd ${{ github.workspace }}
          yarn install --immutable

      - name: Deploy
        run: |
          yarn vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
          yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}
          yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - id: deploy
        run: echo "::set-output name=url::$(yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
