name: 'Vercel Preview and Storybook Test'
on:
  pull_request:
  workflow_dispatch:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          cd ${{ github.workspace }}
          yarn install --immutable

      - name: Deploy
        run: |
          yarn vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
          yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}
          yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - id: deploy
        run: echo "url=$(yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> "$GITHUB_OUTPUT"
      - name: Test
        run: |
          yarn workspace qwik-app test-storybook
        env:
          TARGET_URL: '${{ steps.deploy.outputs.url }}'
